In [33]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score, roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier

In [43]:
data=pd.read_csv("winequality-red.csv")

In [44]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [58]:
data=data.dropna()

In [59]:
x= data.drop(columns='quality')

In [60]:
#y= data['quality']
y=data.quality
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=30)

In [16]:
knn= KNeighborsClassifier()                 #with default values

In [17]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [20]:
knn.score(x_test,y_test)

0.47

In [100]:
pram = {
        
    'n_neighbours':[3,5,7,9,12,13,15,17,21]
       
       }

In [101]:
grid_cv=GridSearchCV(knn,param_grid=pram)
grid_cv

GridSearchCV(estimator=KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1,
                                            weights='distance'),
             param_grid={'n_neighbours': [3, 5, 7, 9, 12, 13, 15, 17, 21]})

In [103]:
grid_cv.fit(x_train, y_train)               #can't fit ask why

ValueError: Invalid parameter n_neighbours for estimator KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance'). Check the list of available parameters with `estimator.get_params().keys()`.

In [37]:
grid_cv.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [ ]:
knn.score(x_test,y_test)

In [ ]:
knn= KNeighborsClassifier(n_neighbors=17,p= 1)         #p provides options to choose dist calc formula, ex- p=1
                                                       # shows manhattan dist is calc

In [104]:
pram = {'n_neighbors':[3,5,7,9,12,13,15,17,21],
        'algorithms' : ['auto','ball_tree','kd_tree','brute'],
        'leaf_size' : [10,15,20,25,30,35,45,50],
        'p': [1,2],
        'weights': ['uniform','distance']
       }

In [105]:
grid_cv=GridSearchCV(knn,param_grid=pram)
grid_cv

GridSearchCV(estimator=KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1,
                                            weights='distance'),
             param_grid={'algorithms': ['auto', 'ball_tree', 'kd_tree',
                                        'brute'],
                         'leaf_size': [10, 15, 20, 25, 30, 35, 45, 50],
                         'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [107]:
grid_cv.fit(x_train, y_train)  ##not able to fit    #knn is not getting supported by Grid CV

In [72]:
grid_cv.best_params_   #gives best parameters

In [73]:
# we got best parameters n_neighbors=21, p=1, weights = 'distance', leaf_size=10, algorithms=auto

In [75]:
knn= KNeighborsClassifier(n_neighbors=21, p=1, weights='distance', leaf_size=10, algorithm='auto')

In [76]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [77]:
knn.score(x_test,y_test)

0.635

In [78]:
#storing our model

import pickle
pickle.dump(knn,open("knn.pk1","wb"))

In [80]:
!ls | grep knn

knn.pk1


In [81]:
#predict from our model

In [83]:
knn.predict(x_test)

In [88]:
knn.predict([x_test.iloc[0]])

array([6])

In [ ]:
##  SVM  -- Support vector machine

In [14]:
from sklearn.svm import SVC       #Support vector classification

In [16]:
svc= SVC()      #kernel trick , used to change dimension of data by applying diff algorithms
svc.fit(x_train,y_train)       #gamma is cofficient of rbf, poly & sigmoid 

In [92]:
svc.score(x_test,y_test)        

0.54

In [93]:
svc1= SVC(kernel='poly') 
svc1.fit(x_train,y_train)

SVC(kernel='poly')

In [94]:
svc1.score(x_test,y_test)

0.515

In [95]:
param ={"kernel":['linear','poly','rbf','sigmoidal']}
svm_grid= GridSearchCV(svc, param_grid=param)
svm_grid.fit(x_train,y_train)

/home/o2bhai/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/home/o2bhai/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/o2bhai/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py", line 226, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/home/o2bhai/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py", line 277, in _dense_fit
    self._probB, self.fit_status_ = libsvm.fit(
  File "sklearn/svm/_libsvm.pyx", line 176, in sklearn.svm._libsvm.fit
ValueError: 'sigmoidal' is not in list

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/o2bhai/anaconda3/lib/python3.9/site-packages/sklearn/mo

GridSearchCV(estimator=SVC(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoidal']})

In [96]:
svm_grid.best_params_

{'kernel': 'linear'}

In [116]:
svc1= SVC(kernel='linear')
svc1.fit(x_train,y_train)

SVC(kernel='linear')

In [117]:
svc1.score(x_test,y_test)

0.59

In [118]:
# SVR support vector regression

In [123]:
data2= pd.read_csv("Admission_Prediction.csv")

In [125]:
data2.head()

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0           1      337.0        118.0  ...  9.65         1             0.92
1           2      324.0        107.0  ...  8.87         1             0.76
2           3        NaN        104.0  ...  8.00         1             0.72
3           4      322.0        110.0  ...  8.67         1             0.80
4           5      314.0        103.0  ...  8.21         0             0.65

[5 rows x 9 columns]

In [138]:
data2.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [134]:
for i in data2.columns:
    if len(data2[data2[i].isnull()==True].index)==0:
        print(f"{i}-no")
    else:
        data2[i]=data2[i].fillna(data2[i].mean())
        data2

Serial No.-no
SOP-no
LOR-no
CGPA-no
Research-no
Chance of Admit-no


In [143]:
x= data2.drop(columns=['Serial No.', 'Chance of Admit'])
x.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0  337.000000        118.0                4.0  4.5  4.5  9.65         1
1  324.000000        107.0                4.0  4.0  4.5  8.87         1
2  316.558763        104.0                3.0  3.0  3.5  8.00         1
3  322.000000        110.0                3.0  3.5  2.5  8.67         1
4  314.000000        103.0                2.0  2.0  3.0  8.21         0

In [145]:
y=data2['Chance of Admit']

In [146]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=30,test_size= 0.20)

In [147]:
from sklearn.svm import SVR

In [148]:
svr= SVR()

In [149]:
svr.fit(x_train,y_train)

SVR()

In [150]:
from sklearn.metrics import r2_score
r2_score(y_test,svr.predict(x_test))

0.6774861142346673

In [151]:
svr.predict(x_test)

array([0.79688575, 0.56869993, 0.70213979, 0.63957666, 0.83300249,
       0.75707761, 0.65994706, 0.68822501, 0.73425829, 0.74644011,
       0.83586246, 0.68361861, 0.7742846 , 0.89252382, 0.81404201,
       0.82819776, 0.55198519, 0.60052276, 0.75981017, 0.71735058,
       0.70996637, 0.70163294, 0.79465708, 0.81204083, 0.77420576,
       0.56782111, 0.63432782, 0.68000782, 0.62334513, 0.58584246,
       0.6721899 , 0.54055777, 0.79251405, 0.64200758, 0.6673232 ,
       0.66244129, 0.6528857 , 0.79952426, 0.55052807, 0.662     ,
       0.57613553, 0.70849189, 0.68005545, 0.66963298, 0.78661726,
       0.6573585 , 0.92081692, 0.63184235, 0.62744472, 0.78123402,
       0.89119762, 0.69692383, 0.79749674, 0.69565313, 0.67689525,
       0.88664598, 0.63801105, 0.53762574, 0.62869004, 0.71534898,
       0.78286732, 0.68986065, 0.73407167, 0.64214697, 0.71423013,
       0.66859242, 0.66567013, 0.62528752, 0.86875038, 0.68531222,
       0.526498  , 0.87626977, 0.6520002 , 0.5400567 , 0.65004

In [152]:
data2.iloc[0]

Serial No.             1.00
GRE Score            337.00
TOEFL Score          118.00
University Rating      4.00
SOP                    4.50
LOR                    4.50
CGPA                   9.65
Research               1.00
Chance of Admit        0.92
Name: 0, dtype: float64

In [155]:
svr.predict([x.iloc[0]])

array([0.89252382])

In [156]:
y[0]    #prediction is close

0.92

In [158]:
# can we use score with svr, i.e svr.score()                     #press shift+tab and see the definitions
svr.score()                                                 #score when called with svr performs regression

In [160]:
svc.score()                              # score when called with svc gives accuracy of svc model

In [ ]:
# Stacking

In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [4]:
data3=pd.read_csv('winequality-red.csv')

In [5]:
data3.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
x= data3.drop(columns='quality')
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [7]:
y=data3.quality

In [18]:
# first we will divide our dataset into train, validate train dataset and test, validate test dataset 
#THEN WE use the train set and test set for training our model
#we make one knn and one svc model from train and test set
#we test our model scores with x_test and y_test set

In [8]:
train , val_train , test , val_test = train_test_split(x,y,random_state=30,test_size=0.15)

In [9]:
x_train , x_test , y_train , y_test = train_test_split(train,test,random_state=30,test_size=0.15)

In [10]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [18]:
svc= SVC()
svc.fit(x_train,y_train)

SVC()

In [12]:
knn.score(x_test,y_test)

0.5343137254901961

In [19]:
svc.score(x_test,y_test)

0.4950980392156863

In [21]:
prediction_knn= knn.predict(val_train)
prediction_svc= svc.predict(val_train)

In [22]:
prediction_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 7, 6, 6, 7, 5, 6, 5, 4,
       6, 7, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5,
       6, 6, 5, 4, 5, 5, 5, 5, 6, 6, 7, 5, 5, 6, 6, 6, 7, 5, 5, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 7, 5, 7, 5, 6, 6, 5, 5, 7, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5,
       5, 6, 7, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 6, 6,
       6, 7, 6, 7, 7, 6, 5, 6, 6, 5, 6, 5, 5, 6, 7, 7, 6, 6, 6, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 7, 6, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 6, 7, 5,
       6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 7, 5, 6, 6, 6, 5, 6, 5, 6])

In [23]:
prediction_svc

array([6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6])

In [ ]:
# we get two model pedictions one from knn and other from svc, we will combine the predictions of the two models 
# and give it as input to the 3rd model
# we treat the prediction from knn as x1 and pred from svc as x2, now x1 and x2 are combined to be used in Random Forest

In [24]:
np.column_stack((prediction_knn,prediction_svc)) # this will be our input

array([[7, 6],
       [5, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [5, 5],
       [5, 6],
       [5, 5],
       [6, 5],
       [5, 5],
       [6, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [6, 5],
       [6, 6],
       [5, 6],
       [6, 5],
       [6, 6],
       [5, 5],
       [5, 6],
       [6, 6],
       [5, 6],
       [5, 5],
       [6, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [6, 6],
       [5, 5],
       [6, 6],
       [6, 6],
       [5, 6],
       [6, 6],
       [6, 6],
       [7, 6],
       [6, 6],
       [6, 6],
       [7, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [4, 6],
       [6, 6],
       [7, 5],
       [6, 6],
       [5, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 5],
       [5, 5],
       [5, 6],
       [5, 5],
       [5, 5],
       [6, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [5, 5],
       [5, 5],
       [6,

In [25]:
input3 =np.column_stack((prediction_knn,prediction_svc))

In [27]:
output= val_test
output.head()

1147    7
659     4
871     5
1333    5
1411    6
Name: quality, dtype: int64

In [28]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
235  6  6
236  5  5
237  6  6
238  5  6
239  6  6

[240 rows x 2 columns]

In [29]:
rf = RandomForestClassifier()

In [35]:
rf.fit(input3,output)

RandomForestClassifier()

In [36]:
rf.score(x_test,y_test)      #it will give error as the rf model is trained on input3(which has 2 features) but
                          # but x_test and y_test has many feayres , so we need to convert the features 2 features 
                        #which are the prediction of knn and svc models from x_test and y_test dataset

ValueError: X has 11 features, but DecisionTreeClassifier is expecting 2 features as input.

In [39]:
knn_out= knn.predict(x_test)
svc_out= svc.predict(x_test)

In [47]:
output_stack1 = np.column_stack((knn_out,svc_out)) #now we'll make a dataset with the predictions 
output_stack1

array([[6, 6],
       [5, 5],
       [6, 6],
       [5, 5],
       [5, 5],
       [7, 6],
       [5, 5],
       [6, 6],
       [6, 5],
       [7, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [5, 5],
       [6, 6],
       [5, 5],
       [6, 6],
       [5, 5],
       [5, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [6, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [5, 5],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [5, 6],
       [4, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [6, 6],
       [5, 5],
       [6, 6],
       [6, 6],
       [6, 6],
       [7, 6],
       [5, 6],
       [5, 6],
       [6, 5],
       [6, 6],
       [5, 5],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [6, 6],
       [5, 5],
       [7, 6],
       [5, 6],
       [5, 5],
       [5, 5],
       [5, 6],
       [5, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [5, 6],
       [5, 6],
       [8, 6],
       [5,

In [45]:
rf.predict(output_stack1)

array([6, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 5, 5,
       5, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6,
       5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5,
       5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5,
       5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5,
       6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 6,
       5, 5, 6, 6, 6, 5])

In [46]:
rf.score(output_stack1,y_test)

0.553921568627451