In [4]:
import numpy as np

In [5]:
import array

In [5]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))                #nd in output means n dimensinal array

numpy.ndarray

In [6]:
np.array([1,2,3,4,"bam",4+8j])                #since we included a string in array the whole elements of array are now strings
                                              #we see dtype U64 which describes the type of string dtype

array(['1', '2', '3', '4', 'bam', '(4+8j)'], dtype='<U64')

In [8]:
np.array([1,2,4,5,6.0])       #similarly here all elements of array converted into float
                             # this is called upcastingb(whic is conversion of dtypes into higher data types ex- int to string or int to float)

array([1., 2., 4., 5., 6.])

In [29]:
np.array([(1,2),(2,3)]) #this is 2d array         #see 2 barackets in output

array([[1, 2],
       [2, 3]])

In [10]:
np.array([[1,3],[3,4]])                       # this is 2d array

array([[1, 3],
       [3, 4]])

In [11]:
np.array([[1,3],[3,4],[5,6]])             # this is 2d array

array([[1, 3],
       [3, 4],
       [5, 6]])

In [15]:
np.array([[1,3],[3,4],[5,6,7]])                 #this will create array but it will give list of array

/tmp/ipykernel_3467/1245926505.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[5,6,7]])


array([list([1, 3]), list([3, 4]), list([5, 6, 7])], dtype=object)

In [14]:
np.array([[[1,3],[3,4]],[[5,6],[7,8]]])             #this is a 3d array   #we can create any dimension of array, it wil be like multiple 2d planes place parallely

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
#creating a n dim array

#np.array([1,2,3],ndmin=3)            # ndmin creates the specified dimension of array
np.array([1,2,3],ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [20]:
np.array([1,2,3], dtype=complex)             #elements as complex no      #set data types to complex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [45]:
arr = np.array([(1,2),(4,5)],dtype = [("a",'<i2'),("b",'i8')])         #changing dtypes 
arr                                                                 # in numpy i2 means int16 and i8 is int64

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [46]:
arr[0][0]
type(arr[0][0])         #dtypes is int  # 

numpy.int16

In [47]:
arr[0][1]
type(arr[0][1])

numpy.int64

In [48]:
arr2 = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)],dtype = [("a",'<i2'),("b",'<i8'),("c",'<i4')])
arr2

array([( 1,  2,  3), ( 4,  5,  6), ( 7,  8,  9), (10, 11, 12)],
      dtype=[('a', '<i2'), ('b', '<i8'), ('c', '<i4')])

In [49]:
np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])    #its 2d array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr2[1][1]
type(arr[1][1])

numpy.int64

In [53]:
##### Now just as we have array we also have matrix            #matrix ia a type of array or we can say matrix is subset of array

#np.mat(arr)

#or

np.matrix(arr)        #both mat and matrix are same

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [54]:


#converting into array

l=[1,2,3,4,5]

In [55]:
np.array(l)

array([1, 2, 3, 4, 5])

In [57]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [58]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [60]:
mat= np.matrix(np.array([1,2,3,4]))
mat

matrix([[1, 2, 3, 4]])

In [61]:
np.asanyarray(mat)          #when we tries converting the matrix to array using anyarray it didn't convert, why

matrix([[1, 2, 3, 4]])

In [62]:
np.asarray(mat)                 ##when we tries converting the matrix to array  using asarray it did convert, why

array([[1, 2, 3, 4]])

In [63]:
# this was becoz matrix is a type of array and so it is already a type of array 
#so anyarray will let it remain matrix

In [66]:

#we can use issubclass to check if matrix is subclass of array in numpy

issubclass(np.ndarray,np.matrix)  #-- checking if ndarray is subclass of matrix ----False --- coz array is parent class
issubclass(np.matrix,np.ndarray)  # matrix is subclass of array - True

True

In [69]:
ar= np.array([[1,2],[3,4]])
ar

array([[1, 2],
       [3, 4]])

In [72]:
a= ar
a

array([[1, 2],
       [3, 4]])

In [74]:
b= np.copy(ar)
b

array([[1, 2],
       [3, 4]])

In [82]:
ar[0][0]= 67                           #arrays are mutable(values can be changes) 
ar                              

array([[67,  2],
       [ 3,  4]])

In [81]:
a                    #changing value of ar changed the value of a, a=ar, here we are referring to ar through a,
                # this is called shallow copy

array([[67,  2],
       [ 3,  4]])

In [83]:
b                  ##changing value of ar did not changed the value of b, b=np.copy(ar), here we have made a copy of ar into b
                 #this is called deep copy

array([[1, 2],
       [3, 4]])

In [86]:
#ar[0:10]
ar[-1]

array([3, 4])

In [88]:
for i in ar:
    print(i)

[67  2]
[3 4]


In [89]:
np.fromfunction(lambda i , j :i==j,(4,4))      # fromfunction is used to creat an ndarray according to the logic defined in it
                                                 # (4,4) describes 4x4 array

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [90]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [92]:
#creating a generator                #range is also a kind of generator
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x7f4377dc4f90>

In [93]:
#ex of generator
def test(x):
    yield x

In [94]:
test(5)

<generator object test at 0x7f4377dc4510>

In [95]:
gen

<generator object <genexpr> at 0x7f4377dc4f90>

In [96]:
np.fromiter(gen,dtype= int)

array([ 0,  1,  4,  9, 16])

In [123]:
# just for example to understand generator , the first line for loop "for i in range(10)" is a type of generator
z= (i for i in range(10))

In [124]:
np.fromiter(z,dtype=int)            #iterating through the generator

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [126]:
np.fromstring('1,2,3,4,5',sep=',')       #iterating through a string

array([1., 2., 3., 4., 5.])

In [127]:
np.fromstring("45 32 56 77 61", sep = ' ', dtype= complex)

array([45.+0.j, 32.+0.j, 56.+0.j, 77.+0.j, 61.+0.j])

In [4]:
arr3= np.array([[1,2,3,4],[5,6,7,8],[1,3,4,6]])

In [5]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 4, 6]])

In [7]:
type(arr3)

numpy.ndarray

In [8]:
arr3.ndim       #dim of array 2d

2

In [10]:
arr3.size     # elements in array

12

In [11]:
arr3.shape     # RxC of array , here 3x4

(3, 4)

In [12]:
arr3.dtype

dtype('int64')

In [18]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]]])
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [15]:
arr2
type(arr2)

numpy.ndarray

In [17]:
arr2.ndim

3

In [31]:
arr4 = np.array([[[1,2,3,4],[5,6,7,8]],[[3,5,4,1],[1,6,3,9]]])
arr4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[3, 5, 4, 1],
        [1, 6, 3, 9]]])

In [32]:
arr4.ndim

3

In [33]:
arr4.shape           #(2,2,4) means we have 2 - 2x4 matrices

(2, 2, 4)

In [35]:
arr5 = np.array([[[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[5,4,3,2]],[[1,6,2,8],[7,4,2,9]],[[3,5,4,1],[1,6,3,9]]]])
arr5

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[2, 3, 4, 5],
         [5, 4, 3, 2]],

        [[1, 6, 2, 8],
         [7, 4, 2, 9]],

        [[3, 5, 4, 1],
         [1, 6, 3, 9]]]])

In [37]:
arr5.ndim         #4d array

4

In [38]:
arr5.shape       #(1,4,2,4) means (start from last) - we have 2x4 matix , 4 times(or 4, 2x4 matrix) in 1 array

(1, 4, 2, 4)

In [43]:
arr5.shape       

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[2, 3, 4, 5],
         [5, 4, 3, 2]]],


       [[[1, 6, 2, 8],
         [7, 4, 2, 9]],

        [[3, 5, 4, 1],
         [1, 6, 3, 9]]]])

In [15]:
arr5 = np.array([[[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[5,4,3,2]]],[[[1,6,2,8],[7,4,2,9]],[[3,5,4,1],[1,6,3,9]]]])
arr5

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[2, 3, 4, 5],
         [5, 4, 3, 2]]],


       [[[1, 6, 2, 8],
         [7, 4, 2, 9]],

        [[3, 5, 4, 1],
         [1, 6, 3, 9]]]])

In [16]:
arr5.shape 

(2, 2, 2, 4)

In [1]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
np.arange(6.6)
np.arange(6.6,9,0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [11]:
np.linspace(1,10,5)     #devide 1-10 in 5 equal parts
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5,4))            # 2 , 5x4 matrixes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [18]:
np.ones((2,3,2))+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [19]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [24]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [29]:
np.linspace(2,4,4)      # includes 2 to 4 into 4 parts, also includes 4
np.linspace(2,4,4,endpoint=False)  # doesn't include 4

array([2. , 2.5, 3. , 3.5])

In [33]:
np.linspace(2,4,4,axis=0)  # 1d array so no axis
#np.linspace(2,4,4,axis=1) # error as array is 1d so axis should be zero

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [48]:
np.linspace([1,6],4,axis=0)      #both 1 and 6 will end at 4, by getting devided in equidistance parts randomly, forming a 1d array
np.linspace([1,6],[8,10],axis=1)    # 1 will end at 8 and 6 will end at 10, by getting devided in equidistance parts randomly, forming a 2d array 

array([[ 1.        ,  1.14285714,  1.28571429,  1.42857143,  1.57142857,
         1.71428571,  1.85714286,  2.        ,  2.14285714,  2.28571429,
         2.42857143,  2.57142857,  2.71428571,  2.85714286,  3.        ,
         3.14285714,  3.28571429,  3.42857143,  3.57142857,  3.71428571,
         3.85714286,  4.        ,  4.14285714,  4.28571429,  4.42857143,
         4.57142857,  4.71428571,  4.85714286,  5.        ,  5.14285714,
         5.28571429,  5.42857143,  5.57142857,  5.71428571,  5.85714286,
         6.        ,  6.14285714,  6.28571429,  6.42857143,  6.57142857,
         6.71428571,  6.85714286,  7.        ,  7.14285714,  7.28571429,
         7.42857143,  7.57142857,  7.71428571,  7.85714286,  8.        ],
       [ 6.        ,  6.08163265,  6.16326531,  6.24489796,  6.32653061,
         6.40816327,  6.48979592,  6.57142857,  6.65306122,  6.73469388,
         6.81632653,  6.89795918,  6.97959184,  7.06122449,  7.14285714,
         7.2244898 ,  7.30612245,  7.3877551 ,  7.

In [54]:
np.linspace([1,6],[8,13],10,axis=1)            #will create a 2d array with 1 to 8 devided into 10parts and 6 to 13 devided into 10 parts

array([[ 1.        ,  1.77777778,  2.55555556,  3.33333333,  4.11111111,
         4.88888889,  5.66666667,  6.44444444,  7.22222222,  8.        ],
       [ 6.        ,  6.77777778,  7.55555556,  8.33333333,  9.11111111,
         9.88888889, 10.66666667, 11.44444444, 12.22222222, 13.        ]])

In [55]:
np.logspace(2,3,5)          #  5 equall part in between log base 2 and log base 3, similar to linepace but just on log table

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [56]:
##  imp ###   from below

In [59]:
d= np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [60]:
d.ndim

1

In [61]:
d.shape

(40,)

In [74]:
d.reshape(40,1)             #reshaped the data into 1 column (40 data - in 1 column)
d.reshape(5,8)             #here we have a 5x8 matrix                #total mutliple should be 40

array([[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
        4.38461538, 4.46153846, 4.53846154],
       [4.61538462, 4.69230769, 4.76923077, 4.84615385, 4.92307692,
        5.        , 5.07692308, 5.15384615],
       [5.23076923, 5.30769231, 5.38461538, 5.46153846, 5.53846154,
        5.61538462, 5.69230769, 5.76923077],
       [5.84615385, 5.92307692, 6.        , 6.07692308, 6.15384615,
        6.23076923, 6.30769231, 6.38461538],
       [6.46153846, 6.53846154, 6.61538462, 6.69230769, 6.76923077,
        6.84615385, 6.92307692, 7.        ]])

In [75]:
d.reshape(1,2,20)       # 1 matrix with 2x20 matrix

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [76]:
d.reshape(2,1,20)          #2 matrix of 1x20

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [77]:
np.random.rand(3)        #it creates 3 random data on the guassian distribution
                        # returns from a normal distribution

array([0.37991497, 0.87106024, 0.96858701])

In [78]:
np.random.randn(5)            # returns from a std normal distribution

array([ 1.16922816, -1.36751032, -1.37598568,  0.66974142, -0.10660922])

In [79]:
np.random.randn(2,2,3)

array([[[-0.38206996,  0.9915812 ,  0.56254562],
        [-0.1878826 ,  0.19676604, -0.32738988]],

       [[ 0.36302948, -0.28979751,  0.14022843],
        [-0.43916813, -0.57354273, -0.10767897]]])

In [80]:
np.random.randint(5,60)   #will generate a random integer bw 5 & 60

49

In [81]:
np.random.randint(5,60, (4,4)) 

array([[29, 11, 12, 42],
       [28, 47,  8, 21],
       [20, 16, 39, 15],
       [51, 44, 52, 21]])

In [82]:
np.random.randn(2,2,3)

array([[[ 0.67941012, -0.16898586,  1.26063143],
        [-0.24093037, -0.44109044,  1.04650698]],

       [[ 0.07455138, -1.88196455,  0.92832437],
        [ 0.89714227, -0.09676966,  0.96374855]]])

In [84]:
arr = np.random.randint(3,9,(3,3))        # in bw 3 to 9 create a 3x3 matrix
arr

array([[5, 5, 6],
       [6, 8, 5],
       [6, 5, 6]])

In [85]:
arr.reshape(1,9)

array([[5, 5, 6, 6, 8, 5, 6, 5, 6]])

In [86]:
arr.reshape(9,1)

array([[5],
       [5],
       [6],
       [6],
       [8],
       [5],
       [6],
       [5],
       [6]])

In [87]:
arr.reshape(1,1,9)     # 1 , 1x9 matrix

array([[[5, 5, 6, 6, 8, 5, 6, 5, 6]]])

In [88]:
arr.reshape(3,1,3)    # 3 , 1x3 matrix

array([[[5, 5, 6]],

       [[6, 8, 5]],

       [[6, 5, 6]]])

In [89]:
arr.max()

8

In [90]:
arr.min()

5

In [93]:
arr= np.random.randint(4,100,(5,5))
arr

array([[18, 22, 42, 41, 75],
       [79, 84, 13, 75, 90],
       [86,  6, 52, 55, 10],
       [91, 51, 62,  7, 36],
       [93, 28, 89, 92, 81]])

In [96]:
arr[3:,2:]        #1st is row, 2nd is column

array([[62,  7, 36],
       [89, 92, 81]])

In [97]:
arr[1:3,1:3]

array([[84, 13],
       [ 6, 52]])

In [99]:
arr[:,0:3]        #this will give from 0 till 3 column

array([[18, 22, 42],
       [79, 84, 13],
       [86,  6, 52],
       [91, 51, 62],
       [93, 28, 89]])

In [100]:
arr[:,[0,3]]    # this will give 0 and 3 column

array([[18, 41],
       [79, 75],
       [86, 55],
       [91,  7],
       [93, 92]])

In [101]:
arr

array([[18, 22, 42, 41, 75],
       [79, 84, 13, 75, 90],
       [86,  6, 52, 55, 10],
       [91, 51, 62,  7, 36],
       [93, 28, 89, 92, 81]])

In [102]:
arr > 10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [103]:
arr[arr>10]          #just filter data of the array acc to condition

array([18, 22, 42, 41, 75, 79, 84, 13, 75, 90, 86, 52, 55, 91, 51, 62, 36,
       93, 28, 89, 92, 81])

In [104]:
arr*arr

array([[ 324,  484, 1764, 1681, 5625],
       [6241, 7056,  169, 5625, 8100],
       [7396,   36, 2704, 3025,  100],
       [8281, 2601, 3844,   49, 1296],
       [8649,  784, 7921, 8464, 6561]])

In [106]:
arr1= np.random.randint(2,4,(3,3))
arr1

array([[2, 2, 3],
       [2, 3, 3],
       [3, 3, 2]])

In [110]:
arr2= np.random.randint(2,6,(3,2))
arr2

array([[4, 2],
       [5, 3],
       [3, 3]])

In [111]:
arr1*arr2      #will not multiply

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [112]:
arr1*arr1     #this is multiplying     # This is happening becoz this is not real matrix mult but just mult indexes in similar position

array([[4, 4, 9],
       [4, 9, 9],
       [9, 9, 4]])

In [113]:
# starting matrix mult

In [114]:
arr1@arr2

array([[27, 19],
       [32, 22],
       [33, 21]])

In [115]:
arr/0

/tmp/ipykernel_2568/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [120]:
arr*2 #mult arr with 2
arr**2  # mult arr wit 2, 2 times

array([[ 36,  44,  84,  82, 150],
       [158, 168,  26, 150, 180],
       [172,  12, 104, 110,  20],
       [182, 102, 124,  14,  72],
       [186,  56, 178, 184, 162]])

In [123]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [127]:
a= np.array([1,2,3,4])
b= np.array([1,2,3])
a

array([1, 2, 3, 4])

In [128]:
a+arr                    #this is originally not matrix addition, it is just adding the array a to every row
      # this is called broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [129]:
b+arr            # b has only 3 elements in row and arr has 4 elements, this will not add

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [134]:
#broadcasting in column
b.reshape(3,1) + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [137]:
b
b.T  # didn't work as b is 1d (1x1)  # should be 2d to transpose

array([1, 2, 3])

In [141]:
c= np.array([[5,6,7]])
c
#c.T

array([[5, 6, 7]])

In [143]:
arr= np.random.rand(5,4)
arr

array([[0.57428656, 0.9434564 , 0.30483957, 0.61945178],
       [0.03394593, 0.49702984, 0.58196346, 0.4298387 ],
       [0.86391129, 0.44770725, 0.99416056, 0.6175861 ],
       [0.33552377, 0.30683895, 0.11703839, 0.38562488],
       [0.4202066 , 0.41269283, 0.04407478, 0.23028404]])

In [144]:
np.sqrt(arr)

array([[0.75781697, 0.97131684, 0.55212278, 0.78705259],
       [0.18424421, 0.70500343, 0.76286529, 0.65562085],
       [0.92946828, 0.6691093 , 0.99707601, 0.78586647],
       [0.57924414, 0.55393045, 0.34210875, 0.62098702],
       [0.64823344, 0.64241173, 0.20993994, 0.47987919]])

In [145]:
np.exp(arr)

array([[1.77586311, 2.56884506, 1.35640738, 1.85790921],
       [1.03452867, 1.64383158, 1.78954869, 1.53700959],
       [2.3724218 , 1.56472056, 2.70245484, 1.85444619],
       [1.39867278, 1.35912206, 1.12416259, 1.47053295],
       [1.52227602, 1.51088085, 1.0450605 , 1.25895755]])

In [146]:
np.log10(arr)

array([[-0.24087134, -0.02527816, -0.51592866, -0.2079925 ],
       [-1.46921232, -0.30361753, -0.23510428, -0.36669448],
       [-0.06353085, -0.34900587, -0.00254347, -0.20930248],
       [-0.47427671, -0.51308951, -0.93167165, -0.41383495],
       [-0.37653713, -0.38437308, -1.35580987, -0.63773617]])

In [152]:
arr = np.random.randint(2,5, (5,5))
arr

array([[4, 3, 2, 4, 4],
       [2, 3, 2, 4, 3],
       [4, 2, 3, 2, 2],
       [4, 4, 4, 4, 2],
       [3, 4, 2, 2, 2]])

In [153]:
np.log10(arr)

array([[0.60205999, 0.47712125, 0.30103   , 0.60205999, 0.60205999],
       [0.30103   , 0.47712125, 0.30103   , 0.60205999, 0.47712125],
       [0.60205999, 0.30103   , 0.47712125, 0.30103   , 0.30103   ],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.30103   ],
       [0.47712125, 0.60205999, 0.30103   , 0.30103   , 0.30103   ]])

In [151]:
arr1

array([[2, 2, 3],
       [2, 3, 3],
       [3, 3, 2]])

In [155]:
np.random.seed(13)             # seed is used to fix random generated data
np.random.rand(2,4)           # other wise if you execute random evry time data time change

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])