In [2]:
import pandas as pd
l = [1,2,3,4,5]

In [3]:
import numpy as np

In [4]:
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
d = {'key' : 'key1', 'title': "kumar1", "mail_id" : "sudha1@gmail.com"}

In [6]:
pd.DataFrame(d,index=['key','title','mail_id'])          #converting dict to dataframe

key   title           mail_id
key      key1  kumar1  sudha1@gmail.com
title    key1  kumar1  sudha1@gmail.com
mail_id  key1  kumar1  sudha1@gmail.com

In [7]:
pd.Series(d)

key                    key1
title                kumar1
mail_id    sudha1@gmail.com
dtype: object

In [8]:
arr = np.random.randn(3,4)
arr

array([[-0.34859571, -0.3311398 ,  0.00687396, -0.66544747],
       [-0.68662404,  0.2332589 ,  1.37595062,  1.24289562],
       [-1.88431816,  0.93829492, -3.39275114, -1.02771268]])

In [9]:
#converting array into dataframe

pd.DataFrame(arr)

0         1         2         3
0 -0.348596 -0.331140  0.006874 -0.665447
1 -0.686624  0.233259  1.375951  1.242896
2 -1.884318  0.938295 -3.392751 -1.027713

In [10]:
pd.DataFrame(arr,index=['a','b','c',])

0         1         2         3
a -0.348596 -0.331140  0.006874 -0.665447
b -0.686624  0.233259  1.375951  1.242896
c -1.884318  0.938295 -3.392751 -1.027713

In [11]:
pd.Series(arr)

ValueError: Data must be 1-dimensional

In [12]:
a= pd.Series(np.array([4,5,6,7,8]),index=['a','b','sudh','kumar','c'])

In [13]:
a

a        4
b        5
sudh     6
kumar    7
c        8
dtype: int64

In [14]:
a['b']

5

In [17]:
a.iloc[2]      # though the indexes doesn't have 2, it still takes 2 and prints the one at the default value at (0,1,2,3,4) index

6

In [18]:
a.loc[0]         #this onnly takes assigned indexes of series or dataframe

KeyError: 0

In [21]:
df = pd.DataFrame(np.random.randint(3,6,(4,5)),index=['a','b','c','d'],columns=['x','y','z','u','v'])
df

x  y  z  u  v
a  3  4  4  3  5
b  5  3  4  5  4
c  3  4  4  3  5
d  3  4  3  3  5

In [25]:
#df.iloc[['c','d'],['z','u']]    #doesn't work, coz iloc doesn't take assigned index value 
df.iloc[[2,3],[2,3]]

z  u
c  4  3
d  3  3

In [26]:
df.loc[['c','d'],['z','u']]

z  u
c  4  3
d  3  3

In [36]:
df.loc["c":"d","x":"u"]

x  y  z  u
c  3  4  4  3
d  3  4  3  3

In [39]:
df.iloc[2:,1:4]

y  z  u
c  4  4  3
d  4  3  3

In [40]:
df

x  y  z  u  v
a  3  4  4  3  5
b  5  3  4  5  4
c  3  4  4  3  5
d  3  4  3  3  5

In [41]:
df2= df

In [42]:
df2

x  y  z  u  v
a  3  4  4  3  5
b  5  3  4  5  4
c  3  4  4  3  5
d  3  4  3  3  5

In [43]:
df2['new'] = df['x'] + df.y

In [44]:
df

x  y  z  u  v  new
a  3  4  4  3  5    7
b  5  3  4  5  4    8
c  3  4  4  3  5    7
d  3  4  3  3  5    7

In [46]:
#df2.drop('x')     #by default drop tries to delete x from index(axis=0) (df.drop('x',axis=0)), but x is not in indexes but in column ,
                  #so we'll have to change axis=1 i.e. columns
    
df2.drop('x',axis=1)      # x column is deleted but is not permanent, to permanently delete it we must use (inplace=True)


y  z  u  v  new
a  4  4  3  5    7
b  3  4  5  4    8
c  4  4  3  5    7
d  4  3  3  5    7

In [58]:
df2

x  y  z  u  v  new
a  3  4  4  3  5    7
b  5  3  4  5  4    8
c  3  4  4  3  5    7
d  3  4  3  3  5    7

In [61]:
#df2.drop('x',axis=1,inplace=True)
df2

y  z  u  v  new
a  4  4  3  5    7
b  3  4  5  4    8
c  4  4  3  5    7
d  4  3  3  5    7

In [56]:
np.random.seed(23)      # will fix the ramdom datas of random.rand       #[rand creates positive data only while randn provides both +ve and -ve]
df3= pd.DataFrame(np.random.randn(4,5),index=['a','b','c','d'],columns=['x','y','z','u','v'])
df3

x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [107]:
#df3<0
df[df3<0]
#df3.values[df3<0]

y    z    u    v  new
a  NaN  4.0  NaN  NaN  NaN
b  3.0  4.0  5.0  NaN  NaN
c  NaN  NaN  NaN  5.0  NaN
d  NaN  NaN  3.0  5.0  NaN

In [73]:
df3.values[df3.values<0]
#df3.values[df3.values<0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [75]:
df3.values[df3.iloc[0:5]<0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [90]:
df3[df3.values<0].index

Index(['a', 'b', 'b', 'b', 'b', 'c', 'c', 'd', 'd', 'd'], dtype='object')

In [92]:
df3.columns

Index(['x', 'y', 'z', 'u', 'v'], dtype='object')

In [93]:
df3.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [100]:
c=df3.values[df3.values<0]
for i in df3.index:
    for j in df3.columns:
        if df3.loc[i,j] in c:
            print (i,j,df3.loc[i,j])

a z -0.7776194131918178
b x -1.0510815639071178
b y -0.3675481161171661
b z -1.1374596907250272
b u -1.3221475225908594
c x -0.34745899102186334
c v -1.0434500017467254
d x -1.0099418765878465
d u -1.8380677677579502
d v -0.9387686311201282


In [111]:
c= df3.values[df3.values<0]
for i in df3.columns:
    for j in df3.index:
        if df3[i][j] in c:
            print (i,j,df3[i][j])

x b -1.0510815639071178
x c -0.34745899102186334
x d -1.0099418765878465
y b -0.3675481161171661
z a -0.7776194131918178
z b -1.1374596907250272
u b -1.3221475225908594
u d -1.8380677677579502
v c -1.0434500017467254
v d -0.9387686311201282


In [120]:
d = {"key1":[1,2,3,4,np.nan],"key2":["sudh","kumar",4,5,6],"key3":[np.nan,np.nan,np.nan,3,8]}
df = pd.DataFrame(d)

In [121]:
df

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
2   3.0      4   NaN
3   4.0      5   3.0
4   NaN      6   8.0

In [122]:
#drop rows or columns with nan values

df.dropna()   # will drop rows with nan values , coz axis=o (default) means rows


key1 key2  key3
3   4.0    5   3.0

In [123]:
df.dropna(axis=1)       #drpping in columns

key2
0   sudh
1  kumar
2      4
3      5
4      6

In [124]:
df.dropna(thresh=0)         #threshold- means the number of non-nan's required to drop the row 
                             #since no row has '0' non-nan values it wont drop any row

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
2   3.0      4   NaN
3   4.0      5   3.0
4   NaN      6   8.0

In [131]:
df.dropna(thresh=3)        #will find at least 3 non-nan values in rows, 

key1 key2  key3
3   4.0    5   3.0

In [133]:
df.dropna(axis=1,thresh=3)

key1   key2
0   1.0   sudh
1   2.0  kumar
2   3.0      4
3   4.0      5
4   NaN      6

In [134]:
#fillna - used to fill replace nan values with my value

df.fillna(567)

key1   key2   key3
0    1.0   sudh  567.0
1    2.0  kumar  567.0
2    3.0      4  567.0
3    4.0      5    3.0
4  567.0      6    8.0

In [135]:
# replacing the nan values with avg value of key1

df.fillna(value=df["key1"].mean())

key1   key2  key3
0   1.0   sudh   2.5
1   2.0  kumar   2.5
2   3.0      4   2.5
3   4.0      5   3.0
4   2.5      6   8.0

In [137]:
df = pd.DataFrame({"name":["ram","sham","dham","pan","bam"],"mail":["ram@gmail.com","sham@gmail.com","dham@gmail.com","pan@gmail.com","bam@gmail.com"],"salary":[100,200,500,200,500]})

In [138]:
df

name            mail  salary
0   ram   ram@gmail.com     100
1  sham  sham@gmail.com     200
2  dham  dham@gmail.com     500
3   pan   pan@gmail.com     200
4   bam   bam@gmail.com     500

In [139]:
df.groupby("name").mean()

salary
name        
bam    500.0
dham   500.0
pan    200.0
ram    100.0
sham   200.0

In [154]:
df.groupby('mail').describe().loc['bam@gmail.com']

salary  count      1.0
        mean     500.0
        std        NaN
        min      500.0
        25%      500.0
        50%      500.0
        75%      500.0
        max      500.0
Name: bam@gmail.com, dtype: float64

In [155]:
df.groupby('mail').describe().loc['bam@gmail.com']['salary']['mean']      #taking out mean value

500.0

In [157]:
#converting row to column

df.groupby('mail').describe().T            #transpose - T

mail          bam@gmail.com  dham@gmail.com  pan@gmail.com  ram@gmail.com  \
salary count            1.0             1.0            1.0            1.0   
       mean           500.0           500.0          200.0          100.0   
       std              NaN             NaN            NaN            NaN   
       min            500.0           500.0          200.0          100.0   
       25%            500.0           500.0          200.0          100.0   
       50%            500.0           500.0          200.0          100.0   
       75%            500.0           500.0          200.0          100.0   
       max            500.0           500.0          200.0          100.0   

mail          sham@gmail.com  
salary count             1.0  
       mean            200.0  
       std               NaN  
       min             200.0  
       25%             200.0  
       50%             200.0  
       75%             200.0  
       max             200.0

In [ ]:
#concatting data

In [158]:
arr1 = np.random.randn(3,4)

In [159]:
arr2 = np.random.randn(3,4)

In [160]:
arr3 = np.random.randn(3,4)

In [163]:
df1 = pd.DataFrame(arr1,index=[0,1,2],columns=["A","B","C","D"])

In [164]:
df2 = pd.DataFrame(arr2,index=[0,1,2],columns=["A","B","C","D"])

In [165]:
df3 = pd.DataFrame(arr3,index=[0,1,2],columns=["A","B","C","D"])

In [166]:
pd.concat([df1,df2,df3],axis=1)

A         B         C         D         A         B         C  \
0 -0.201841  1.045371  0.538162  0.812119  0.728876  1.968435 -0.547788   
1  0.241106 -0.952510 -0.136267  1.267248 -2.506230  0.146960  0.606195   
2  0.173634 -1.223255  1.415320  0.457711  0.013422  0.935945  0.420623   

          D         A         B         C         D  
0 -0.679418 -0.071324 -0.045438  1.040886 -0.094035  
1 -0.022539 -0.420844 -0.551989 -0.121098  0.190141  
2  0.411620  0.512137  0.131538 -0.331617 -1.632386

In [169]:
df4=pd.concat([df1,df2,df3])

In [170]:
df4.loc[0]

A         B         C         D
0 -0.201841  1.045371  0.538162  0.812119
0  0.728876  1.968435 -0.547788 -0.679418
0 -0.071324 -0.045438  1.040886 -0.094035

In [171]:
df4.iloc[0]

A   -0.201841
B    1.045371
C    0.538162
D    0.812119
Name: 0, dtype: float64

In [176]:
df2 = pd.DataFrame(arr2,index=[3,4,5],columns=["A","B","C","D"])
df3 = pd.DataFrame(arr3,index=[6,7,8],columns=["A","B","C","D"])

In [178]:
pd.concat([df1,df2,df3],axis=1).fillna(0)

A         B         C         D         A         B         C  \
0 -0.201841  1.045371  0.538162  0.812119  0.000000  0.000000  0.000000   
1  0.241106 -0.952510 -0.136267  1.267248  0.000000  0.000000  0.000000   
2  0.173634 -1.223255  1.415320  0.457711  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.728876  1.968435 -0.547788   
4  0.000000  0.000000  0.000000  0.000000 -2.506230  0.146960  0.606195   
5  0.000000  0.000000  0.000000  0.000000  0.013422  0.935945  0.420623   
6  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          D         A         B         C         D  
0  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.000000  0.000000  0.000000  0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  
3 -0.679418  0.000000  0.000000  0.000000  0.000000  
4 -0.022539  0.000000  0.000000  0.000000  0.000000  
5  0.411620  0.000000  0.000000  0.000000  0.000000  
6  0.000000 -0.071324 -0.045438  1.040886 -0.094035  
7  0.000000 -0.420844 -0.551989 -0.121098  0.190141  
8  0.000000  0.512137  0.131538 -0.331617 -1.632386

In [179]:
df1

A         B         C         D
0 -0.201841  1.045371  0.538162  0.812119
1  0.241106 -0.952510 -0.136267  1.267248
2  0.173634 -1.223255  1.415320  0.457711

In [180]:
df2

A         B         C         D
3  0.728876  1.968435 -0.547788 -0.679418
4 -2.506230  0.146960  0.606195 -0.022539
5  0.013422  0.935945  0.420623  0.411620

In [181]:
np.random.seed(23)
ar1= np.random.randn(3,4)
np.random.seed(23)
ar2= np.random.randn(3,4)
df11 = pd.DataFrame(arr2,columns=["A","B","C","D"],index=[0,1,2])
df22 = pd.DataFrame(arr2,columns=["A","B","C","D"],index=[3,4,5])

In [182]:
df11

A         B         C         D
0  0.728876  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620

In [183]:
df22

A         B         C         D
3  0.728876  1.968435 -0.547788 -0.679418
4 -2.506230  0.146960  0.606195 -0.022539
5  0.013422  0.935945  0.420623  0.411620

In [184]:
pd.merge(df11,df22,on ='A')  #it merges columns of 2 or more dataset, taking a column of datasets that have common value

A       B_x       C_x       D_x       B_y       C_y       D_y
0  0.728876  1.968435 -0.547788 -0.679418  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620  0.935945  0.420623  0.411620

In [186]:
pd.merge(df11,df22,on =['A','B'])

A         B       C_x       D_x       C_y       D_y
0  0.728876  1.968435 -0.547788 -0.679418 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620  0.420623  0.411620

In [188]:
dfa=pd.DataFrame({'key': ['k0','k8','k2','k3'],
                  'A': ['A0','A1','A2','A3'],
                  'B': ['B0','B1','B2','B3']})

dfb=pd.DataFrame({'key': ['k0','k1','k2','k3'],
                  'A': ['A0','A1','A2','A3'],
                  'B': ['B0','B1','B2','B3']})

In [189]:
pd.merge(dfa,dfb,on='key')        # keycolumn with common values will be 

key A_x B_x A_y B_y
0  k0  A0  B0  A0  B0
1  k2  A2  B2  A2  B2
2  k3  A3  B3  A3  B3

In [194]:
dfx=pd.DataFrame({'key1': ['k0','k8','k2','k3'],                 #join operations can be done wih common row index
                  'A': ['A0','A1','A2','A3'],                 #but columns should not be same
                  'B': ['B0','B1','B2','B3']})

dfy=pd.DataFrame({'key2': ['k0','k1','k2','k3'],
                  'C': ['A0','A1','A2','A3'],
                  'D': ['B0','B1','B2','B3']})

In [198]:
dfx

key1   A   B
0   k0  A0  B0
1   k8  A1  B1
2   k2  A2  B2
3   k3  A3  B3

In [197]:
dfy

key2   C   D
0   k0  A0  B0
1   k1  A1  B1
2   k2  A2  B2
3   k3  A3  B3

In [199]:
dfx.join(dfy)

key1   A   B key2   C   D
0   k0  A0  B0   k0  A0  B0
1   k8  A1  B1   k1  A1  B1
2   k2  A2  B2   k2  A2  B2
3   k3  A3  B3   k3  A3  B3